import "~/styles/globals.css";
import { type Metadata } from "next";
import {
  ProjectAdminHeader,
  ProjectAdminPageSideMenu,
} from "~/components/dashboard/project/admin";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface Props {
  children: React.ReactNode;
}

export default function ProjectAdminPageLayout({ children }: Props) {
  return (
    <main className="h-screen w-full">
      <ProjectAdminHeader />
      <main className="flex h-full w-full">
        <ProjectAdminPageSideMenu />
        <div className="h-full w-full p-2 pt-18">
          <div className="custom-scrollbar bg-secondary h-full w-full overflow-y-scroll rounded-xl">
            {children}
          </div>
        </div>
      </main>
    </main>
  );
}
